version: '3.8'
services:
  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - cache:/data
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 3000:80

    # links:
    #   - cache
    # volumes:
    #   - ./:/src
# volumes:
#   cache:
#     driver: local